#Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-secure6
  namespace: data-team
spec:
  sparkConf:
    # Note: If you are executing the application as a K8 user that MapR can verify,
    #       you do not need to specify a spark.mapr.user.secret
    spark.mapr.user.secret: spark-user-secret-secure
    # Note: You do not need to specify a spark.eventLog.dir
    #       it will be auto-generated with the pattern "maprfs:///apps/spark/<namespace>"
    spark.eventLog.dir: "maprfs:///apps/spark"
  type: Scala
  sparkVersion: 2.4.5
  mode: cluster
  image: gcr.io/mapr-252711/spark-2.4.5:202010301117C
  imagePullPolicy: Always
  imagePullSecrets:
  - imagepull
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/mapr/spark/spark-2.4.5/examples/jars/spark-examples_2.12-2.4.5.0-mapr-700.jar"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.5
    # Note: You do not need to specify a serviceAccount
    #       it will be auto-generated referencing the pre-existing "hpe-<namespace>"
    #serviceAccount: hpe-sampletenant
  executor:
    cores: 1
    coreLimit: "1000m"
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.5

